import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  // Create Provider component to wrap app with SessionProvider
  return (      
    <html lang="en" suppressHydrationWarning>
          <body className={inter.className}>
                <Provider>
                  {children}
                </Provider>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
            </body>
    </html>
  )
}
